name: viinon
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  collection: ^1.17.2
  equatable: ^2.0.5
  flutter_spinkit: ^5.2.0
  intl: ^0.18.1
  get: ^4.6.6
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/slider/
    - assets/animations/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
        - family: Roboto-Bold
          fonts:
              - asset: assets/fonts/Roboto-Bold.ttf
        - family: Roboto-Regular
          fonts:
              - asset: assets/fonts/Roboto-Regular.ttf
        - family: Roboto-Medium
          fonts:
              - asset: assets/fonts/Roboto-Medium.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_gen:
  integrations:
    flutter_svg: true
  colors:
    enabled: true
    inputs:
      - assets/colors/colors.xml
  fonts:
    enabled: true